name: ReleaseNote

on:
  push:
    branches: main
    
env:
  HOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  REPO_NAME: LarvelTemplate
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false